# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "subarch-select" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ekg/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: acb41a936637d7488997646f61f386f1869bd91aa093e0f48d6299c95c9f9851
    patches:
      - makefile_tweaks.patch

build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - cpu_features >=0.8

test:
  commands:
    - subarch-select sse /bin/echo -- SSE detected | grep "SSE detected"

about:
  home: https://github.com/ekg/subarch-select
  summary: 'Pick an executable based on CPU capabilities'
  description: |
    Pick an executable based on CPU capabilities and pass the remaining command
    line flags to the target program. Designed for x86-64 systems, including
    the x86-64 microarchitecture levels (x86-64-v2, x86-64-v3, x86-64-v4).
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ekg/subarch-select/

extra:
  recipe-maintainers:
    - mr-c
    - milot-mirdita
